function generateLoader(domain, username, scriptName, secretKey) {
  // Encode URI components to handle spaces/symbols in names
  const safeUsername = encodeURIComponent(username);
  const safeScriptName = encodeURIComponent(scriptName);
  
  return `
-- Secure Loader for GameGuardian
-- Generated by Script Delivery System

local url = "${domain}/${safeUsername}/${safeScriptName}"
local secret = "${secretKey}"

function decrypt(data, key)
    -- Base64 decoding
    local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    data = string.gsub(data, '[^'..b..'=]', '')
    local result = {}
    local temp = 0
    local bits = 0
    
    for i = 1, #data do
        local char = string.sub(data, i, i)
        if char == '=' then break end
        
        local index = string.find(b, char) - 1
        temp = temp * 64 + index
        bits = bits + 6
        
        if bits >= 8 then
            bits = bits - 8
            local byte = math.floor(temp / (2 ^ bits))
            temp = temp % (2 ^ bits)
            
            -- XOR Decrypt immediately
            local keyIndex = (#result % #key) + 1
            local keyByte = string.byte(string.sub(key, keyIndex, keyIndex))
            local decryptedByte = byte ~ keyByte
            
            table.insert(result, string.char(decryptedByte))
        end
    end
    return table.concat(result)
end

local r = gg.makeRequest({
  url = url,
  headers = {
    ["X-GG-KEY"] = secret,
    ["User-Agent"] = "GameGuardian"
  }
})

if r.code == 200 then
    local content = r.content
    if content then
        local success, err = pcall(function()
            local decoded = decrypt(content, secret)
            local func = load(decoded)
            func()
        end)
        if not success then
            gg.alert("Failed to execute script: " .. tostring(err))
        end
    else
        gg.alert("Empty response from server")
    end
else
    gg.alert("Failed to load script. Status: " .. r.code)
end
`;
}

module.exports = { generateLoader };
